name 'liferay'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures liferay'
long_description 'Installs/Configures liferay'
version '0.1.0'
